---
name: 'Kulala CLI action'
description: 'Execute HTTP files with Kulala'
author: 'Yaro Apletov'
branding:
  color: 'purple'
  icon: 'moon'
runs:
  using: "composite"
  steps:
  - name: Setup Neovim
    uses: rhysd/action-setup-vim@v1
    with:
      neovim: true

  - name: Setup Nvim-treesitter
    uses: actions/checkout@v4
    with:
      repository: nvim-treesitter/nvim-treesitter
      path: nvim-treesitter

  - name: Symlink nvim-tresitter to XDG_DATA_HOME
    run: |
      mkdir -p "$XDG_DATA_HOME"
      ln -s "$GITHUB_WORKSPACE/nvim-tresitter" "$XDG_DATA_HOME/nvim-treesitter"
    shell: bash
    env:
      XDG_DATA_HOME: /home/runner/.local/share/nvim

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '22'

  - name: Setup Kulala CI
    uses: actions/checkout@v4
    with:
      repository: mistweaverco/kulala.nvim
      path: kulala.nvim

  - name: Set GitHub Env
    run: |
      echo "$KULALA_CLI_PATH" >> "${GITHUB_PATH}"
    shell: bash
    env:
      KULALA_CLI_PATH: ${{ github.workspace }}/kulala.nvim/lua/cli

  - name: Update Kulala CI
    run: kulala_ci.sh
    shell: bash
