### Get example - JSONPlaceholder
GET https://jsonplaceholder.typicode.com/posts/1
Accept: application/json

### Get all posts
GET https://jsonplaceholder.typicode.com/posts
Accept: application/json

### Create a new post
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "Test Post",
  "body": "This is a test post from Kulala Docker",
  "userId": 1
}

### Update a post
PUT https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
  "id": 1,
  "title": "Updated Post",
  "body": "This post has been updated",
  "userId": 1
}

### Delete a post
DELETE https://jsonplaceholder.typicode.com/posts/1